var catalogo = require("./catalago.json")
//console.log(catalogo.data)
var catalogoString = JSON.stringify(catalogo)
console.log(catalogoString)
var catalogoObjeto = JSON.parse(catalogoString)
console.log(catalogoObjeto)